import { AVPlaybackSource } from 'expo-av';

export type TuneType = 'hp' | 'jig' | 'slowhp' | 'tradhp' | 'tradjig';

export type Tune = {
  key: string;
  type: TuneType;
  name: string;
  value: AVPlaybackSource;
  defaultSpeed: number;
  minSpeed: number;
  maxSpeed: number;
};

export const AllTunes: Tune[] = [
  {
    key: 'hp_ace_and_deuce_of_pipering_107',
    name: 'Ace And Deuce Of Pipering',
    value: require('@/assets/audio/hp_ace_and_deuce_of_pipering_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_bonapartes_retreat_107',
    name: "Bonaparte's Retreat",
    value: require('@/assets/audio/hp_bonapartes_retreat_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_job_of_journeywork_107',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/hp_job_of_journeywork_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_king_of_the_fairies_107',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/hp_king_of_the_fairies_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_madame_bonaparte_107',
    name: 'Madame Bonaparte',
    value: require('@/assets/audio/hp_madame_bonaparte_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_planxty_davis_107',
    name: 'Planxty Davis',
    value: require('@/assets/audio/hp_planxty_davis_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_rodneys_glory_107',
    name: "Rodney's Glory",
    value: require('@/assets/audio/hp_rodneys_glory_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_battle_of_arklow_107',
    name: 'The Battle Of Arklow',
    value: require('@/assets/audio/hp_the_battle_of_arklow_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_blue_eyed_rascal_107',
    name: 'The Blue Eyed Rascal',
    value: require('@/assets/audio/hp_the_blue_eyed_rascal_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_downfall_of_paris_107',
    name: 'The Downfall Of Paris',
    value: require('@/assets/audio/hp_the_downfall_of_paris_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_four_masters_107',
    name: 'The Four Masters',
    value: require('@/assets/audio/hp_the_four_masters_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_garden_of_daisies_107',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/hp_the_garden_of_daisies_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_hunt_107',
    name: 'The Hunt',
    value: require('@/assets/audio/hp_the_hunt_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_kilkenny_races_107',
    name: 'The Kilkenny Races',
    value: require('@/assets/audio/hp_the_kilkenny_races_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_lodge_road_107',
    name: 'The Lodge Road',
    value: require('@/assets/audio/hp_the_lodge_road_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_piper_107',
    name: 'The Piper',
    value: require('@/assets/audio/hp_the_piper_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_rambling_rake_107',
    name: 'The Rambling Rake',
    value: require('@/assets/audio/hp_the_rambling_rake_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_roving_pedlar_107',
    name: 'The Roving Pedlar',
    value: require('@/assets/audio/hp_the_roving_pedlar_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_the_white_blanket_107',
    name: 'The White Blanket',
    value: require('@/assets/audio/hp_the_white_blanket_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'hp_youghal_harbour_107',
    name: 'Youghal Harbour',
    value: require('@/assets/audio/hp_youghal_harbour_107.m4a'),
    type: 'hp',
    defaultSpeed: 107,
    minSpeed: 100,
    maxSpeed: 120,
  },
  {
    key: 'jig_hurry_the_jug_70',
    name: 'Hurry The Jug',
    value: require('@/assets/audio/jig_hurry_the_jug_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_is_the_big_man_within_70',
    name: 'Is The Big Man Within',
    value: require('@/assets/audio/jig_is_the_big_man_within_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_jockey_to_the_fair_70',
    name: 'Jockey To The Fair',
    value: require('@/assets/audio/jig_jockey_to_the_fair_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_miss_browns_fancy_70',
    name: "Miss Brown's Fancy",
    value: require('@/assets/audio/jig_miss_browns_fancy_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_planxty_drury_70',
    name: 'Planxty Drury',
    value: require('@/assets/audio/jig_planxty_drury_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_planxty_hugh_odonnell_70',
    name: "Planxty Hugh O'Donnell",
    value: require('@/assets/audio/jig_planxty_hugh_odonnell_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_planxty_irwin_70',
    name: 'Planxty Irwin',
    value: require('@/assets/audio/jig_planxty_irwin_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_rub_the_bag_70',
    name: 'Rub The Bag',
    value: require('@/assets/audio/jig_rub_the_bag_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_sprig_of_shillelagh_70',
    name: 'Sprig Of Shillelagh',
    value: require('@/assets/audio/jig_sprig_of_shillelagh_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_blackthorn_stick_70',
    name: 'The Blackthorn Stick',
    value: require('@/assets/audio/jig_the_blackthorn_stick_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_charlady_70',
    name: 'The Charlady',
    value: require('@/assets/audio/jig_the_charlady_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_donegal_rambler_70',
    name: 'The Donegal Rambler',
    value: require('@/assets/audio/jig_the_donegal_rambler_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_drunken_gauger_70',
    name: 'The Drunken Gauger',
    value: require('@/assets/audio/jig_the_drunken_gauger_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_fiddler_around_the_fairy_tree_70',
    name: 'The Fiddler Around The Fairy Tree',
    value: require('@/assets/audio/jig_the_fiddler_around_the_fairy_tree_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_humours_of_bandon_70',
    name: 'The Humours Of Bandon',
    value: require('@/assets/audio/jig_the_humours_of_bandon_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_hurling_boys_70',
    name: 'The Hurling Boys',
    value: require('@/assets/audio/jig_the_hurling_boys_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_orange_rogue_70',
    name: 'The Orange Rogue',
    value: require('@/assets/audio/jig_the_orange_rogue_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_storyteller_70',
    name: 'The Storyteller',
    value: require('@/assets/audio/jig_the_storyteller_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_three_sea_captains_70',
    name: 'The Three Sea Captains',
    value: require('@/assets/audio/jig_the_three_sea_captains_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_vanishing_lake_70',
    name: 'The Vanishing Lake',
    value: require('@/assets/audio/jig_the_vanishing_lake_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'jig_the_wandering_musician_70',
    name: 'The Wandering Musician',
    value: require('@/assets/audio/jig_the_wandering_musician_70.m4a'),
    type: 'jig',
    defaultSpeed: 70,
    minSpeed: 60,
    maxSpeed: 80,
  },
  {
    key: 'slowhp_ace_and_deuce_of_pipering_80',
    name: 'Ace And Deuce Of Pipering',
    value: require('@/assets/audio/slowhp_ace_and_deuce_of_pipering_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_bonapartes_retreat_80',
    name: "Bonaparte's Retreat",
    value: require('@/assets/audio/slowhp_bonapartes_retreat_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_job_of_journeywork_80',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/slowhp_job_of_journeywork_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_king_of_the_fairies_80',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/slowhp_king_of_the_fairies_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_madame_bonaparte_80',
    name: 'Madame Bonaparte',
    value: require('@/assets/audio/slowhp_madame_bonaparte_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_planxty_davis_80',
    name: 'Planxty Davis',
    value: require('@/assets/audio/slowhp_planxty_davis_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_rodneys_glory_80',
    name: "Rodney's Glory",
    value: require('@/assets/audio/slowhp_rodneys_glory_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_blue_eyed_rascal_80',
    name: 'The Blue Eyed Rascal',
    value: require('@/assets/audio/slowhp_the_blue_eyed_rascal_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_downfall_of_paris_80',
    name: 'The Downfall Of Paris',
    value: require('@/assets/audio/slowhp_the_downfall_of_paris_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_four_masters_80',
    name: 'The Four Masters',
    value: require('@/assets/audio/slowhp_the_four_masters_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_garden_of_daisies_80',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/slowhp_the_garden_of_daisies_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_hunt_80',
    name: 'The Hunt',
    value: require('@/assets/audio/slowhp_the_hunt_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_kilkenny_races_80',
    name: 'The Kilkenny Races',
    value: require('@/assets/audio/slowhp_the_kilkenny_races_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_lodge_road_80',
    name: 'The Lodge Road',
    value: require('@/assets/audio/slowhp_the_lodge_road_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_piper_80',
    name: 'The Piper',
    value: require('@/assets/audio/slowhp_the_piper_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_rambling_rake_80',
    name: 'The Rambling Rake',
    value: require('@/assets/audio/slowhp_the_rambling_rake_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_roving_pedlar_80',
    name: 'The Roving Pedlar',
    value: require('@/assets/audio/slowhp_the_roving_pedlar_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_the_white_blanket_80',
    name: 'The White Blanket',
    value: require('@/assets/audio/slowhp_the_white_blanket_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'slowhp_youghal_harbour_80',
    name: 'Youghal Harbour',
    value: require('@/assets/audio/slowhp_youghal_harbour_80.m4a'),
    type: 'slowhp',
    defaultSpeed: 80,
    minSpeed: 75,
    maxSpeed: 85,
  },
  {
    key: 'tradhp_job_of_journeywork_140',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/tradhp_job_of_journeywork_140.m4a'),
    type: 'tradhp',
    defaultSpeed: 140,
    minSpeed: 110,
    maxSpeed: 160,
  },
  {
    key: 'tradhp_king_of_the_fairies_140',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/tradhp_king_of_the_fairies_140.m4a'),
    type: 'tradhp',
    defaultSpeed: 140,
    minSpeed: 110,
    maxSpeed: 160,
  },
  {
    key: 'tradhp_the_blackbird_140',
    name: 'The Blackbird',
    value: require('@/assets/audio/tradhp_the_blackbird_140.m4a'),
    type: 'tradhp',
    defaultSpeed: 140,
    minSpeed: 110,
    maxSpeed: 160,
  },
  {
    key: 'tradhp_the_garden_of_daisies_140',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/tradhp_the_garden_of_daisies_140.m4a'),
    type: 'tradhp',
    defaultSpeed: 140,
    minSpeed: 110,
    maxSpeed: 160,
  },
  {
    key: 'tradhp_the_white_blanket_140',
    name: 'The White Blanket',
    value: require('@/assets/audio/tradhp_the_white_blanket_140.m4a'),
    type: 'tradhp',
    defaultSpeed: 140,
    minSpeed: 110,
    maxSpeed: 160,
  },
  {
    key: 'tradjig_jockey_to_the_fair_90',
    name: 'Jockey To The Fair',
    value: require('@/assets/audio/tradjig_jockey_to_the_fair_90.m4a'),
    type: 'tradjig',
    defaultSpeed: 90,
    minSpeed: 80,
    maxSpeed: 100,
  },
  {
    key: 'tradjig_st_patricks_day_90',
    name: "St. Patrick's Day",
    value: require('@/assets/audio/tradjig_st_patricks_day_90.m4a'),
    type: 'tradjig',
    defaultSpeed: 90,
    minSpeed: 80,
    maxSpeed: 100,
  },
  {
    key: 'tradjig_the_three_sea_captains_90',
    name: 'The Three Sea Captains',
    value: require('@/assets/audio/tradjig_the_three_sea_captains_90.m4a'),
    type: 'tradjig',
    defaultSpeed: 90,
    minSpeed: 80,
    maxSpeed: 100,
  },
];

let tuneMap: Map<string, Tune> | undefined = undefined;

export const getTuneMap = function (): Map<string, Tune> {
  if (!tuneMap) {
    tuneMap = new Map<string, Tune>();
    AllTunes.forEach((tune) => {
      tuneMap?.set(tune.key, tune);
    });
  }
  return tuneMap;
};
