import { AVPlaybackSource } from 'expo-av';

export type Tune = {
  key: string;
  type: 'hp' | 'jig' | 'slowhp' | 'tradhp' | 'tradjig';
  name: string;
  value: AVPlaybackSource;
  defaultSpeed: number;
};

export const AllTunes: Tune[] = [
  {
    key: 'aceanddeuceofpipering-107',
    type: 'hp',
    name: 'Ace And Deuce Of Pipering',
    value: require('@/assets/audio/hp-Ace And Deuce Of Pipering-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'bonapartesretreat-107',
    type: 'hp',
    name: "Bonaparte's Retreat",
    value: require("@/assets/audio/hp-Bonaparte's Retreat-107.m4a"),
    defaultSpeed: 107,
  },
  {
    key: 'jobofjourneywork-107',
    type: 'hp',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/hp-Job Of Journeywork-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'kingofthefairies-107',
    type: 'hp',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/hp-King Of The Fairies-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'madamebonaparte-107',
    type: 'hp',
    name: 'Madame Bonaparte',
    value: require('@/assets/audio/hp-Madame Bonaparte-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'planxtydavis-107',
    type: 'hp',
    name: 'Planxty Davis',
    value: require('@/assets/audio/hp-Planxty Davis-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'rodneysglory-107',
    type: 'hp',
    name: "Rodney's Glory",
    value: require("@/assets/audio/hp-Rodney's Glory-107.m4a"),
    defaultSpeed: 107,
  },
  {
    key: 'thebattleofarklow-107',
    type: 'hp',
    name: 'The Battle Of Arklow',
    value: require('@/assets/audio/hp-The Battle Of Arklow-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'theblueeyedrascal-107',
    type: 'hp',
    name: 'The Blue Eyed Rascal',
    value: require('@/assets/audio/hp-The Blue Eyed Rascal-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thedownfallofparis-107',
    type: 'hp',
    name: 'The Downfall Of Paris',
    value: require('@/assets/audio/hp-The Downfall Of Paris-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thefourmasters-107',
    type: 'hp',
    name: 'The Four Masters',
    value: require('@/assets/audio/hp-The Four Masters-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thegardenofdaisies-107',
    type: 'hp',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/hp-The Garden Of Daisies-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thehunt-107',
    type: 'hp',
    name: 'The Hunt',
    value: require('@/assets/audio/hp-The Hunt-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thekilkennyraces-107',
    type: 'hp',
    name: 'The Kilkenny Races',
    value: require('@/assets/audio/hp-The Kilkenny Races-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thelodgeroad-107',
    type: 'hp',
    name: 'The Lodge Road',
    value: require('@/assets/audio/hp-The Lodge Road-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thepiper-107',
    type: 'hp',
    name: 'The Piper',
    value: require('@/assets/audio/hp-The Piper-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'theramblingrake-107',
    type: 'hp',
    name: 'The Rambling Rake',
    value: require('@/assets/audio/hp-The Rambling Rake-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'therovingpedlar-107',
    type: 'hp',
    name: 'The Roving Pedlar',
    value: require('@/assets/audio/hp-The Roving Pedlar-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'thewhiteblanket-107',
    type: 'hp',
    name: 'The White Blanket',
    value: require('@/assets/audio/hp-The White Blanket-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'youghalharbour-107',
    type: 'hp',
    name: 'Youghal Harbour',
    value: require('@/assets/audio/hp-Youghal Harbour-107.m4a'),
    defaultSpeed: 107,
  },
  {
    key: 'hurrythejug-70',
    type: 'jig',
    name: 'Hurry The Jug',
    value: require('@/assets/audio/jig-Hurry The Jug-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'isthebigmanwithin-70',
    type: 'jig',
    name: 'Is The Big Man Within',
    value: require('@/assets/audio/jig-Is The Big Man Within-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'jockeytothefair-70',
    type: 'jig',
    name: 'Jockey To The Fair',
    value: require('@/assets/audio/jig-Jockey To The Fair-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'missbrownsfancy-70',
    type: 'jig',
    name: "Miss Brown's Fancy",
    value: require("@/assets/audio/jig-Miss Brown's Fancy-70.m4a"),
    defaultSpeed: 70,
  },
  {
    key: 'planxtydrury-70',
    type: 'jig',
    name: 'Planxty Drury',
    value: require('@/assets/audio/jig-Planxty Drury-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'planxtyhughodonnell-70',
    type: 'jig',
    name: "Planxty Hugh O'Donnell",
    value: require("@/assets/audio/jig-Planxty Hugh O'Donnell-70.m4a"),
    defaultSpeed: 70,
  },
  {
    key: 'planxtyirwin-70',
    type: 'jig',
    name: 'Planxty Irwin',
    value: require('@/assets/audio/jig-Planxty Irwin-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'rubthebag-70',
    type: 'jig',
    name: 'Rub The Bag',
    value: require('@/assets/audio/jig-Rub The Bag-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'sprigofshillelagh-70',
    type: 'jig',
    name: 'Sprig Of Shillelagh',
    value: require('@/assets/audio/jig-Sprig Of Shillelagh-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'theblackthornstick-70',
    type: 'jig',
    name: 'The Blackthorn Stick',
    value: require('@/assets/audio/jig-The Blackthorn Stick-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thecharlady-70',
    type: 'jig',
    name: 'The Charlady',
    value: require('@/assets/audio/jig-The Charlady-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thedonegalrambler-70',
    type: 'jig',
    name: 'The Donegal Rambler',
    value: require('@/assets/audio/jig-The Donegal Rambler-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thedrunkengauger-70',
    type: 'jig',
    name: 'The Drunken Gauger',
    value: require('@/assets/audio/jig-The Drunken Gauger-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thefiddleraroundthefairytree-70',
    type: 'jig',
    name: 'The Fiddler Around The Fairy Tree',
    value: require('@/assets/audio/jig-The Fiddler Around The Fairy Tree-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thehumoursofbandon-70',
    type: 'jig',
    name: 'The Humours Of Bandon',
    value: require('@/assets/audio/jig-The Humours Of Bandon-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thehurlingboys-70',
    type: 'jig',
    name: 'The Hurling Boys',
    value: require('@/assets/audio/jig-The Hurling Boys-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'theorangerogue-70',
    type: 'jig',
    name: 'The Orange Rogue',
    value: require('@/assets/audio/jig-The Orange Rogue-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thestoryteller-70',
    type: 'jig',
    name: 'The Storyteller',
    value: require('@/assets/audio/jig-The Storyteller-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thethreeseacaptains-70',
    type: 'jig',
    name: 'The Three Sea Captains',
    value: require('@/assets/audio/jig-The Three Sea Captains-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thevanishinglake-70',
    type: 'jig',
    name: 'The Vanishing Lake',
    value: require('@/assets/audio/jig-The Vanishing Lake-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'thewanderingmusician-70',
    type: 'jig',
    name: 'The Wandering Musician',
    value: require('@/assets/audio/jig-The Wandering Musician-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'planxty-hugh',
    type: 'jig',
    name: "Planxty Hugh O'Donnell",
    value: require('@/assets/audio/jig-planxty-hugh-odonnell-70.m4a'),
    defaultSpeed: 70,
  },
  {
    key: 'aceanddeuceofpipering-80',
    type: 'slowhp',
    name: 'Ace And Deuce Of Pipering',
    value: require('@/assets/audio/slowhp-Ace And Deuce Of Pipering-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'bonapartesretreat-80',
    type: 'slowhp',
    name: "Bonaparte's Retreat",
    value: require("@/assets/audio/slowhp-Bonaparte's Retreat-80.m4a"),
    defaultSpeed: 80,
  },
  {
    key: 'jobofjourneywork-80',
    type: 'slowhp',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/slowhp-Job Of Journeywork-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'kingofthefairies-80',
    type: 'slowhp',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/slowhp-King Of The Fairies-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'madamebonaparte-80',
    type: 'slowhp',
    name: 'Madame Bonaparte',
    value: require('@/assets/audio/slowhp-Madame Bonaparte-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'planxtydavis-80',
    type: 'slowhp',
    name: 'Planxty Davis',
    value: require('@/assets/audio/slowhp-Planxty Davis-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'rodneysglory-80',
    type: 'slowhp',
    name: "Rodney's Glory",
    value: require("@/assets/audio/slowhp-Rodney's Glory-80.m4a"),
    defaultSpeed: 80,
  },
  {
    key: 'theblueeyedrascal-80',
    type: 'slowhp',
    name: 'The Blue Eyed Rascal',
    value: require('@/assets/audio/slowhp-The Blue Eyed Rascal-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thedownfallofparis-80',
    type: 'slowhp',
    name: 'The Downfall Of Paris',
    value: require('@/assets/audio/slowhp-The Downfall Of Paris-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thefourmasters-80',
    type: 'slowhp',
    name: 'The Four Masters',
    value: require('@/assets/audio/slowhp-The Four Masters-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thegardenofdaisies-80',
    type: 'slowhp',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/slowhp-The Garden Of Daisies-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thehunt-80',
    type: 'slowhp',
    name: 'The Hunt',
    value: require('@/assets/audio/slowhp-The Hunt-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thekilkennyraces-80',
    type: 'slowhp',
    name: 'The Kilkenny Races',
    value: require('@/assets/audio/slowhp-The Kilkenny Races-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thelodgeroad-80',
    type: 'slowhp',
    name: 'The Lodge Road',
    value: require('@/assets/audio/slowhp-The Lodge Road-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thepiper-80',
    type: 'slowhp',
    name: 'The Piper',
    value: require('@/assets/audio/slowhp-The Piper-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'theramblingrake-80',
    type: 'slowhp',
    name: 'The Rambling Rake',
    value: require('@/assets/audio/slowhp-The Rambling Rake-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'therovingpedlar-80',
    type: 'slowhp',
    name: 'The Roving Pedlar',
    value: require('@/assets/audio/slowhp-The Roving Pedlar-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'thewhiteblanket-80',
    type: 'slowhp',
    name: 'The White Blanket',
    value: require('@/assets/audio/slowhp-The White Blanket-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'youghalharbour-80',
    type: 'slowhp',
    name: 'Youghal Harbour',
    value: require('@/assets/audio/slowhp-Youghal Harbour-80.m4a'),
    defaultSpeed: 80,
  },
  {
    key: 'jobofjourneywork-140',
    type: 'tradhp',
    name: 'Job Of Journeywork',
    value: require('@/assets/audio/tradhp-Job Of Journeywork-140.m4a'),
    defaultSpeed: 140,
  },
  {
    key: 'kingofthefairies-140',
    type: 'tradhp',
    name: 'King Of The Fairies',
    value: require('@/assets/audio/tradhp-King Of The Fairies-140.m4a'),
    defaultSpeed: 140,
  },
  {
    key: 'theblackbird-140',
    type: 'tradhp',
    name: 'The Blackbird',
    value: require('@/assets/audio/tradhp-The Blackbird-140.m4a'),
    defaultSpeed: 140,
  },
  {
    key: 'thegardenofdaisies-140',
    type: 'tradhp',
    name: 'The Garden Of Daisies',
    value: require('@/assets/audio/tradhp-The Garden Of Daisies-140.m4a'),
    defaultSpeed: 140,
  },
  {
    key: 'thewhiteblanket-140',
    type: 'tradhp',
    name: 'The White Blanket',
    value: require('@/assets/audio/tradhp-The White Blanket-140.m4a'),
    defaultSpeed: 140,
  },
  {
    key: 'jockeytothefair-90',
    type: 'tradjig',
    name: 'Jockey To The Fair',
    value: require('@/assets/audio/tradjig-Jockey To The Fair-90.m4a'),
    defaultSpeed: 90,
  },
  {
    key: 'stpatricksday-90',
    type: 'tradjig',
    name: "St. Patrick's Day",
    value: require("@/assets/audio/tradjig-St. Patrick's Day-90.m4a"),
    defaultSpeed: 90,
  },
  {
    key: 'thethreeseacaptains-90',
    type: 'tradjig',
    name: 'The Three Sea Captains',
    value: require('@/assets/audio/tradjig-The Three Sea Captains-90.m4a'),
    defaultSpeed: 90,
  },
];

let tuneMap: Map<string, Tune> | undefined = undefined;

export const getTuneMap = function (): Map<string, Tune> {
  if (!tuneMap) {
    tuneMap = new Map<string, Tune>();
    AllTunes.forEach((tune) => {
      tuneMap?.set(tune.key, tune);
    });
  }
  return tuneMap;
};
