packages:
  - apps/*
  - packages/*
patchedDependencies:
  expo-dev-launcher: patches/expo-dev-launcher.patch
  expo-observe: patches/expo-observe.patch
  react-native-reanimated: patches/react-native-reanimated.patch
allowBuilds:
  unrs-resolver: true
nodeLinker: hoisted
overrides:
  react-native-reanimated: 4.6.0
