packages:
  - apps/*
  - packages/*
patchedDependencies:
  expo-dev-launcher: patches/expo-dev-launcher.patch
  expo-observe: patches/expo-observe.patch
  expo-modules-jsi: patches/expo-modules-jsi.patch
  react-native-reanimated: patches/react-native-reanimated.patch
allowBuilds:
  unrs-resolver: true
nodeLinker: hoisted
overrides:
  react-native-reanimated: 4.6.0
  react-native: npm:react-native-tvos@0.88.0-0rc2
  react-native-tvos: 0.88.0-0rc2
  react-native-worklets: 0.12.2
minimumReleaseAgeExclude:
  - '@react-native-tvos/virtualized-lists@0.88.0-0rc2'
  - react-native-tvos@0.88.0-0rc2
